/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package routinegenerator2;

import Routine.DynamicDatas;
import Routine.InitialDatas;
import Routine.Main;
import java.util.List;
import javax.swing.table.TableColumn;

/**
 *
 * @author power
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    Main main=new Main();
    public Frame() {
        initComponents();
        this.jLabel1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("GenerateRoutine");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("__Help__");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addGap(127, 127, 127)
                .addComponent(jButton3)
                .addContainerGap(127, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setInitiationText(){
        String table="<html>Generating Your Routines<br/>"
                + "please wait patiently...</html>";
        this.jLabel1.setText(table);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setInitiationText();
        List<String> routines=main.getRoutines();
        String num="The number of tables Produced is "+routines.size();
        String html="<html>\n<head>\n<title>The Possible routines</title>\n"
                + "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "</head>\n<body>\n"
                + "<div class=\"abc\">The List of all the possible routines that can"
                + "be generated from the given list of subjects and the free time of the"
                + " teachers are as follows:</div>";
        for(int i=0;i<routines.size();i++){
            html+=routines.get(i)+"<br/><br/>";
        }
        html+="</body></html>";
        FileHandler.WriteToFile.writeToFile("routines.html", html);
        this.jLabel1.setText("<html>The Routine is Generated.<br/>"
                + ""+num+""
                + "<br/>The program created a file named routines.html<br/>"
                + " which contains the solution<br/>"
                + "s to the routine problem<br/>Thanks for trying me!!!</html>");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // help button
        //InitialDatas.printAllTeachersDetails();
        //InitialDatas.availabilityTable.printListUsefulTimeSlots();
        String help="<html>Right in the context of this program, there should be a file named<br/>"
                + "RG_DATA which should contain a file named \'rg_general.txt\'<br/>"
                + "This is the file where you specify the subjects to be taught in a class in the form<br/>"
                + "subjectName : teacherName : periodsPerWeek<br/><br/>"
                + "Then inside the folder RG_TEACHERS, in files named teacherName.txt<br/>"
                + "specify the free time of the teacher in the form <br/>"
                + "day: period<br/>"
                + "Click the 'generateRoutine' button up and your solution will be generated";
        this.jLabel1.setText(help);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
